### ISSUE TITLE
cant he rows be re-ordered with jquery UI?

### ISSUE THREAD

**Issue by patagoniahiker** [fire1/DuplicateElement#3]
It would be a very nice feature if the rows could be sorted/reordered.

**Comment by fire1** [comment]
JQuery UI is not supported 

You can add field input type="number" for selecting required order. 
If you want... I can give you an example script

**Comment by patagoniahiker** [comment]
:+1:  I would really appreciate the script to do that.

**Comment by fire1** [comment]
This is an example only!

You must add this input as new column to your form: 
&lt;input type=&quot;number&quot; value=&quot;1&quot; name=&quot;order&quot; class=&quot;form-control order-controller&quot;&gt;

This script will set value to class "order-controller"  

```
        $(function () {
            $('#additional-field-model').duplicateElement({
                "class_remove": ".remove-this-field",
                "class_create": ".create-new-field",
                onCreate: function (el) {
                    var controller = el.find('.order-controller');
                    controller.val(parseInt(controller.val() )+ 1); // Add new position
                },
                onRemove:  function (el) {
                    var controller = el.find('.order-controller');
                    controller.val(parseInt(controller.val() )- 1); // Remove position
                }
            });
        });
```

**Comment by patagoniahiker** [comment]
:100:  thanks again!

I am closing it, can you ensure it works on the full row. Currently its only working on 1 column rows for me. Do I need to use some special Bootstrapping classes as well?

And I can wire it up to this below correct, the `$(this).serialize();` is sending the full JSON array correct?

```
var ajax_request = {};
var counter = 0;
$(function () {
    $('#additional-field-model').duplicateElement({
        "class_remove": ".remove-this-field",
        "class_create": ".create-new-field",
        onCreate: function (el) {
            el.on('change', ' input, select, textarea', function () {
                ajax_request[++counter]= $(this).serialize();
                $.post( "test.php",ajax_request);
                console.log(ajax_request);
            });
        }
    });
});
```
